# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 178aa64e62a99c4bc26f2b198975f2c62271d69f2aafdb3d17188b86b82b4764e1882b61804eb65996276005fbf970c3bd6b046f5b29cca1ca59661c3a2fa984

test:
  secret_key_base: 6a2544ceddd77386ed462a0fce486b1aa3e9975a64f619e7faae49b2b9bbd9c4bb3bfa77931d52dd54dd64ed5ec9284dd460b7c0fb13fc4811673a22796377b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
